### ISSUE TITLE
Fix (Travis-CI) tests

### ISSUE THREAD

**Issue by rugk** [saltyrtc/saltyrtc-task-webrtc-js#12]
Maybe you should fix that: https://travis-ci.org/saltyrtc/saltyrtc-task-webrtc-js/builds/215432512

(It does not look good… :smiley: )

**Comment by rugk** [comment]
[Still failing](https://travis-ci.org/saltyrtc/saltyrtc-task-webrtc-js/builds) as it seems.

**Comment by lgrahl** [comment]
Irrelevant as @dbrgn switched to Circle CI.
