### ISSUE TITLE
Buffer candidates

### ISSUE THREAD

**Issue by dbrgn** [saltyrtc/saltyrtc-task-webrtc-js#4]

**Comment by lgrahl** [comment]
Idea: https://github.com/saltyrtc/saltyrtc-meta/issues/4#issuecomment-249373678

**Comment by dbrgn** [comment]
I decided to add 5ms of buffering. It is a very short amount of time but it might catch one or two more candidates than no timeout at all :)

**Comment by dbrgn** [comment]
Proof that it works:

![screenshot](https://tmp.dbrgn.ch/screenshots/20161020112646-d1yqiqqa.png)
